### ISSUE TITLE
Unknown Tag --utf8 bei HLint

### ISSUE THREAD

**Issue by jjonly** [ob-fun-ws17/ob-fun-ws17#1]
Für alle, die auch die Fehlermeldung bekommen: unknow tag --utf8
Einfach in der Datei HLint.hs die Zeile
  hints <- hlint $ "--utf8" : arguments 
ersetzen durch
  hints <- hlint arguments
(Nachträglich Schreibfehler editiert)
Dann sollte auch die statische Codeanalyse funktionieren.

**Comment by obcode** [comment]
Die neue Zeile müsste
````
hints <- hlint arguments
````

lauten, oder?

**Comment by jjonly** [comment]
Richtig, unvorsichtig kopiert, danke. Habe es editiert.

**Comment by obcode** [comment]
Danke! Ich habe es auf dem Blatt korrigiert: https://ob.cs.hm.edu/dropbox/lectures/fun/exercises/Blatt01.json
